spring:
  application:
    name: ${APP_NAME}
  datasource:
    url: jdbc:postgresql://${APP_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
    ignore-missing-migrations: true
    out-of-order: true
    url: jdbc:postgresql://${APP_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  servlet:
    context-path: /api
management:
  endpoint:
    health:
      show-details: always
# Show details of health endpoint