spring:
  application:
    name: ${APP_NAME}
  profiles:
    active: ${PROFILE}
server:
  servlet:
    context-path: /api
springdoc:
  api-docs:
    path: /v1/petclinic-api-docs
  swagger-ui:
    path: /petclinic-doc.html