ALTER TABLE owners
    ADD created_date TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE owners
    ADD updated_date TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE pets
    ADD created_date TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE pets
    ADD updated_date TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE specialities
    ADD created_date TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE specialities
    ADD updated_date TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE types
    ADD created_date TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE types
    ADD updated_date TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE vets
    ADD created_date TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE vets
    ADD updated_date TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE visits
    ADD created_date TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE visits
    ADD updated_date TIMESTAMP WITHOUT TIME ZONE;